name: syslog-ng-native-deps
builder:
  name: BalabitBuilder
  flags: "no-configure no-make-dist no-local-build"
platforms:
  - aix-6.1/powerpc
  - windows-2012/amd64
  - windows-2012/i386
  - linux-glibc2.11/amd64